'use strict';
// Question bank: 13 categories x 25 questions, each in Arabic (q/a) and English (qE/aE).
// Every question has exactly ONE clean answer per language (shown in the vote list).
// Other spellings or names that should also count as "the real answer" when a player
// types them as a bluff go in `alt` (Arabic) / `altE` (English).

const QUESTIONS = {
  general: [
    {q:"كم لون في قوس قزح؟",a:"سبعة",qE:"How many colors in a rainbow?",aE:"Seven"},
    {q:"ما الرياضة الأكثر شعبية في العالم؟",a:"كرة القدم",alt:["الكرة"],qE:"Most popular sport in the world?",aE:"Football",altE:["Soccer"]},
    {q:"كم يوماً في السنة الكبيسة؟",a:"366",qE:"How many days in a leap year?",aE:"366"},
    {q:"ما العملة الرسمية لليابان؟",a:"الين",qE:"Official currency of Japan?",aE:"Yen"},
    {q:"ما أسرع حيوان بري؟",a:"الفهد",qE:"Fastest land animal?",aE:"Cheetah",alt:["الشيتا"]},
    {q:"كم ثانية في الساعة؟",a:"3600",qE:"Seconds in an hour?",aE:"3600"},
    {q:"ما أكبر حيوان على الأرض؟",a:"الحوت الأزرق",qE:"Largest animal on Earth?",aE:"Blue whale"},
    {q:"كم ساعة في اليوم؟",a:"24",qE:"Hours in a day?",aE:"24"},
    {q:"ما لون السماء الصافية؟",a:"أزرق",qE:"Color of a clear sky?",aE:"Blue"},
    {q:"كم جناح للفراشة؟",a:"أربعة",qE:"How many wings does a butterfly have?",aE:"Four"},
    {q:"ما أكثر مشروب استهلاكاً بعد الماء؟",a:"الشاي",qE:"Most consumed drink after water?",aE:"Tea"},
    {q:"ما الكوكب الأحمر؟",a:"المريخ",qE:"Which planet is the Red Planet?",aE:"Mars"},
    {q:"كم حرف في الأبجدية الإنجليزية؟",a:"26",qE:"Letters in the English alphabet?",aE:"26"},
    {q:"ما أطول حيوان بري؟",a:"الزرافة",qE:"Tallest land animal?",aE:"Giraffe"},
    {q:"كم قارة في العالم؟",a:"سبع",qE:"How many continents?",aE:"Seven"},
    {q:"ما الشهر الأول في السنة؟",a:"يناير",qE:"First month of the year?",aE:"January"},
    {q:"كم عدد أيام الأسبوع؟",a:"سبعة",qE:"Days in a week?",aE:"Seven"},
    {q:"ما المعدن الأغلى؟",a:"الذهب",qE:"Most precious common metal?",aE:"Gold"},
    {q:"كم دقيقة في الساعة؟",a:"60",qE:"Minutes in an hour?",aE:"60"},
    {q:"ما الحيوان الذي يُسمى سفينة الصحراء؟",a:"الجمل",qE:"Which animal is called ship of the desert?",aE:"Camel"},
    {q:"ما أصغر قارة؟",a:"أوقيانوسيا",qE:"Smallest continent?",aE:"Oceania",alt:["أستراليا"],altE:["Australia"]},
    {q:"ما لون الشمس عند الغروب؟",a:"برتقالي",qE:"Color of the sun at sunset?",aE:"Orange"},
    {q:"كم عين للإنسان؟",a:"اثنتان",qE:"How many eyes does a human have?",aE:"Two"},
    {q:"ما أكبر طائر في العالم؟",a:"النعامة",qE:"Largest bird in the world?",aE:"Ostrich"},
    {q:"ما أصغر كوكب في المجموعة الشمسية؟",a:"عطارد",qE:"Smallest planet in our solar system?",aE:"Mercury"},
  ],
  geography: [
    {q:"ما أصغر دولة في العالم؟",a:"الفاتيكان",qE:"Smallest country in the world?",aE:"Vatican City"},
    {q:"ما أطول نهر في العالم؟",a:"النيل",qE:"Longest river in the world?",aE:"The Nile"},
    {q:"ما عاصمة أستراليا؟",a:"كانبرا",qE:"Capital of Australia?",aE:"Canberra"},
    {q:"ما أكبر محيط؟",a:"المحيط الهادئ",qE:"Largest ocean?",aE:"Pacific Ocean"},
    {q:"ما عاصمة اليابان؟",a:"طوكيو",qE:"Capital of Japan?",aE:"Tokyo"},
    {q:"ما أكبر صحراء في العالم؟",a:"الصحراء الكبرى",qE:"Largest desert?",aE:"Sahara"},
    {q:"ما عاصمة البرازيل؟",a:"برازيليا",qE:"Capital of Brazil?",aE:"Brasilia"},
    {q:"أين يقع برج إيفل؟",a:"باريس",qE:"Where is the Eiffel Tower?",aE:"Paris"},
    {q:"ما أعلى جبل في العالم؟",a:"إيفرست",qE:"Tallest mountain?",aE:"Everest"},
    {q:"ما أكبر جزيرة؟",a:"غرينلاند",qE:"Largest island?",aE:"Greenland"},
    {q:"ما عاصمة كندا؟",a:"أوتاوا",qE:"Capital of Canada?",aE:"Ottawa"},
    {q:"أين يقع تاج محل؟",a:"الهند",qE:"Where is the Taj Mahal?",aE:"India"},
    {q:"ما عاصمة تركيا؟",a:"أنقرة",qE:"Capital of Turkey?",aE:"Ankara"},
    {q:"ما أطول سلسلة جبلية؟",a:"الأنديز",qE:"Longest mountain range?",aE:"Andes"},
    {q:"ما عاصمة ألمانيا؟",a:"برلين",qE:"Capital of Germany?",aE:"Berlin"},
    {q:"ما أكبر دولة مساحة؟",a:"روسيا",qE:"Largest country by area?",aE:"Russia"},
    {q:"ما عاصمة إسبانيا؟",a:"مدريد",qE:"Capital of Spain?",aE:"Madrid"},
    {q:"في أي قارة تقع مصر؟",a:"أفريقيا",qE:"Which continent is Egypt on?",aE:"Africa"},
    {q:"ما عاصمة إيطاليا؟",a:"روما",qE:"Capital of Italy?",aE:"Rome"},
    {q:"ما أكبر بحيرة عذبة في العالم؟",a:"بحيرة سوبيريور",qE:"Largest freshwater lake?",aE:"Lake Superior"},
    {q:"ما أعمق نقطة في المحيط؟",a:"خندق ماريانا",qE:"Deepest point in the ocean?",aE:"Mariana Trench"},
    {q:"ما عاصمة الأرجنتين؟",a:"بوينس آيرس",qE:"Capital of Argentina?",aE:"Buenos Aires"},
    {q:"ما عاصمة النرويج؟",a:"أوسلو",qE:"Capital of Norway?",aE:"Oslo"},
    {q:"ما البلد الذي يشتهر بالأهرامات؟",a:"مصر",qE:"Country famous for pyramids?",aE:"Egypt"},
    {q:"ما عاصمة السويد؟",a:"ستوكهولم",qE:"Capital of Sweden?",aE:"Stockholm"},
  ],
  history: [
    {q:"في أي عام اكتُشفت أمريكا؟",a:"1492",qE:"When was America discovered?",aE:"1492"},
    {q:"من بنى الأهرامات؟",a:"المصريون القدماء",qE:"Who built the pyramids?",aE:"Ancient Egyptians"},
    {q:"متى بدأت الحرب العالمية الأولى؟",a:"1914",qE:"When did WWI begin?",aE:"1914"},
    {q:"من أول رئيس أمريكي؟",a:"جورج واشنطن",qE:"First US president?",aE:"George Washington"},
    {q:"في أي عام سقط جدار برلين؟",a:"1989",qE:"When did the Berlin Wall fall?",aE:"1989"},
    {q:"من اخترع المصباح الكهربائي؟",a:"إديسون",qE:"Who invented the light bulb?",aE:"Edison",altE:["Thomas Edison"],alt:["توماس إديسون"]},
    {q:"متى تأسست الأمم المتحدة؟",a:"1945",qE:"When was the UN founded?",aE:"1945"},
    {q:"من اكتشف الجاذبية؟",a:"نيوتن",qE:"Who discovered gravity?",aE:"Newton",altE:["Isaac Newton"],alt:["إسحاق نيوتن"]},
    {q:"من أول من مشى على القمر؟",a:"نيل أرمسترونغ",qE:"First person on the Moon?",aE:"Neil Armstrong"},
    {q:"في أي عام غرقت تايتانيك؟",a:"1912",qE:"When did Titanic sink?",aE:"1912"},
    {q:"من اخترع الهاتف؟",a:"غراهام بيل",qE:"Who invented the telephone?",aE:"Alexander Graham Bell",altE:["Graham Bell","Bell"],alt:["بيل","ألكسندر غراهام بيل"]},
    {q:"من بنى سور الصين العظيم؟",a:"الصينيون",qE:"Who built the Great Wall of China?",aE:"The Chinese"},
    {q:"متى انتهت الحرب العالمية الثانية؟",a:"1945",qE:"When did WWII end?",aE:"1945"},
    {q:"من قاد ثورة الهند؟",a:"غاندي",qE:"Who led India's independence?",aE:"Gandhi"},
    {q:"من فتح القسطنطينية؟",a:"محمد الفاتح",qE:"Who conquered Constantinople?",aE:"Mehmed the Conqueror"},
    {q:"ما أقدم حضارة؟",a:"السومرية",qE:"Oldest civilization?",aE:"Sumerian"},
    {q:"من اخترع الطباعة؟",a:"غوتنبرغ",qE:"Who invented printing press?",aE:"Gutenberg"},
    {q:"في أي عام وصل الإنسان للقمر؟",a:"1969",qE:"When did humans reach the Moon?",aE:"1969"},
    {q:"من رسم الموناليزا؟",a:"دافنشي",qE:"Who painted the Mona Lisa?",aE:"Da Vinci",altE:["Leonardo da Vinci","Leonardo"],alt:["ليوناردو دافنشي"]},
    {q:"من اخترع الديناميت؟",a:"نوبل",qE:"Who invented dynamite?",aE:"Alfred Nobel"},
    {q:"في أي عام بدأت الثورة الفرنسية؟",a:"1789",qE:"When did the French Revolution begin?",aE:"1789"},
    {q:"من كان آخر فراعنة مصر؟",a:"كليوباترا",qE:"Who was the last pharaoh?",aE:"Cleopatra"},
    {q:"في أي قرن اكتُشف البارود؟",a:"التاسع",qE:"In which century was gunpowder discovered?",aE:"9th century"},
    {q:"من مؤسس الدولة العثمانية؟",a:"عثمان الأول",qE:"Founder of the Ottoman Empire?",aE:"Osman I"},
    {q:"متى اكتُشف النفط في السعودية؟",a:"1938",qE:"When was oil discovered in Saudi Arabia?",aE:"1938"},
  ],
  science: [
    {q:"ما العنصر الأكثر وفرة في الكون؟",a:"الهيدروجين",qE:"Most abundant element in the universe?",aE:"Hydrogen"},
    {q:"كم كوكب في المجموعة الشمسية؟",a:"ثمانية",qE:"Planets in our solar system?",aE:"Eight"},
    {q:"ما أكبر عضو في الجسم؟",a:"الجلد",qE:"Largest organ in the body?",aE:"Skin"},
    {q:"كم عظمة في جسم الإنسان؟",a:"206",qE:"Bones in adult human body?",aE:"206"},
    {q:"ما أقرب كوكب للشمس؟",a:"عطارد",qE:"Closest planet to Sun?",aE:"Mercury"},
    {q:"ما درجة غليان الماء؟",a:"100 مئوية",qE:"Boiling point of water?",aE:"100°C"},
    {q:"ما أصلب معدن طبيعي؟",a:"الألماس",qE:"Hardest natural mineral?",aE:"Diamond"},
    {q:"ما أكبر كوكب في المجموعة الشمسية؟",a:"المشتري",qE:"Largest planet?",aE:"Jupiter"},
    {q:"ما الرمز الكيميائي للذهب؟",a:"Au",qE:"Chemical symbol for gold?",aE:"Au"},
    {q:"ما أسرع سرعة في الكون؟",a:"سرعة الضوء",qE:"Fastest speed in the universe?",aE:"Speed of light"},
    {q:"كم كروموسوم للإنسان؟",a:"46",qE:"Human chromosomes?",aE:"46"},
    {q:"ما أصغر وحدة حية؟",a:"الخلية",qE:"Smallest unit of life?",aE:"Cell"},
    {q:"ما الغاز الأكثر في الغلاف الجوي؟",a:"النيتروجين",qE:"Most common gas in atmosphere?",aE:"Nitrogen"},
    {q:"ما درجة تجمد الماء؟",a:"صفر مئوية",qE:"Freezing point of water?",aE:"0°C"},
    {q:"ما وحدة قياس القوة؟",a:"نيوتن",qE:"Unit of force?",aE:"Newton",altE:["Isaac Newton"],alt:["إسحاق نيوتن"]},
    {q:"كم لتر دم في الجسم؟",a:"خمسة",qE:"Liters of blood in the body?",aE:"About 5"},
    {q:"ما المعدن الأكثر توصيلاً للكهرباء؟",a:"الفضة",qE:"Most conductive metal?",aE:"Silver"},
    {q:"ما العضو الذي ينقي الدم؟",a:"الكلية",qE:"Organ that filters blood?",aE:"Kidney"},
    {q:"ما الحمض النووي الذي يحمل الجينات؟",a:"DNA",qE:"Nucleic acid carrying genes?",aE:"DNA"},
    {q:"ما الغاز الذي تمتصه النباتات؟",a:"ثاني أكسيد الكربون",qE:"Gas absorbed by plants?",aE:"Carbon dioxide"},
    {q:"ما أبعد كوكب عن الشمس؟",a:"نبتون",qE:"Farthest planet from Sun?",aE:"Neptune"},
    {q:"كم عدد فصائل الدم الرئيسية؟",a:"أربع",qE:"Main blood types?",aE:"Four"},
    {q:"ما سرعة الصوت تقريباً؟",a:"343 م/ث",qE:"Speed of sound approximately?",aE:"343 m/s"},
    {q:"ما العضو المسؤول عن التوازن؟",a:"الأذن الداخلية",qE:"Organ responsible for balance?",aE:"Inner ear"},
    {q:"ما أخف غاز في الطبيعة؟",a:"الهيدروجين",qE:"Lightest gas?",aE:"Hydrogen"},
  ],
  sports: [
    {q:"كم مدة شوط كرة القدم؟",a:"45 دقيقة",qE:"Length of one football half?",aE:"45 minutes"},
    {q:"كم لاعب في فريق كرة السلة؟",a:"خمسة",qE:"Players on a basketball team?",aE:"Five"},
    {q:"كم حلقة أولمبية؟",a:"خمس",qE:"How many Olympic rings?",aE:"Five"},
    {q:"ما مسافة الماراثون؟",a:"42 كم",qE:"Marathon distance?",aE:"42 km"},
    {q:"ما لون بطاقة الطرد؟",a:"حمراء",qE:"Color of ejection card?",aE:"Red"},
    {q:"أين أقيمت أول بطولة كأس عالم؟",a:"الأوروغواي",qE:"Where was first World Cup?",aE:"Uruguay"},
    {q:"كم لاعب في فريق الكريكيت؟",a:"11",qE:"Players on a cricket team?",aE:"11"},
    {q:"ما الرياضة الوطنية لكندا؟",a:"الهوكي",qE:"National sport of Canada?",aE:"Ice hockey"},
    {q:"في أي رياضة يوجد الإيس؟",a:"التنس",qE:"Sport with an 'ace'?",aE:"Tennis"},
    {q:"كم جولة في الملاكمة المحترفة؟",a:"12",qE:"Rounds in pro boxing?",aE:"12"},
    {q:"ما الرياضة التي تُلعب على الجليد بعصا؟",a:"الهوكي",qE:"Sport played on ice with a stick?",aE:"Hockey"},
    {q:"كم لاعب في فريق البيسبول؟",a:"تسعة",qE:"Players on a baseball team?",aE:"Nine"},
    {q:"ما الرياضة الأشهر في الهند؟",a:"الكريكيت",qE:"Most popular sport in India?",aE:"Cricket"},
    {q:"كم شوط في مباراة التنس كحد أقصى؟",a:"خمسة",qE:"Max sets in a tennis match?",aE:"Five"},
    {q:"من أي بلد نشأت الجودو؟",a:"اليابان",qE:"Where did judo originate?",aE:"Japan"},
    {q:"ما وزن كرة القدم الرسمية تقريباً؟",a:"450 غرام",qE:"Weight of official football?",aE:"450 grams"},
    {q:"كم لاعب في فريق كرة الماء؟",a:"سبعة",qE:"Players on water polo team?",aE:"Seven"},
    {q:"ما الرياضة التي يُستخدم فيها المضرب والريشة؟",a:"الريشة الطائرة",qE:"Sport with racket and shuttlecock?",aE:"Badminton"},
    {q:"كم تبلغ مدة مباراة كرة السلة؟",a:"48 دقيقة",qE:"NBA game duration?",aE:"48 minutes"},
    {q:"ما أقدم رياضة أولمبية؟",a:"المصارعة",qE:"Oldest Olympic sport?",aE:"Wrestling"},
    {q:"كم يبلغ ارتفاع شبكة التنس؟",a:"متر تقريباً",qE:"Height of tennis net?",aE:"About 1 meter"},
    {q:"ما الرياضة الأشهر في أمريكا؟",a:"كرة القدم الأمريكية",qE:"Most popular sport in the US?",aE:"American Football"},
    {q:"كم يبلغ طول حمام السباحة الأولمبي؟",a:"50 متر",qE:"Length of Olympic swimming pool?",aE:"50 meters"},
    {q:"ما اسم الكرة في رياضة الغولف؟",a:"كرة الغولف",qE:"What's the ball in golf called?",aE:"Golf ball"},
    {q:"من أي بلد نشأت كرة القدم الحديثة؟",a:"إنجلترا",qE:"Where did modern football originate?",aE:"England"},
  ],
  entertainment: [
    {q:"ما أشهر فيلم ديزني للرسوم المتحركة؟",a:"الأسد الملك",qE:"Most famous Disney animated film?",aE:"The Lion King"},
    {q:"ما اسم روبوت حرب النجوم الشهير؟",a:"R2-D2",qE:"Famous Star Wars robot?",aE:"R2-D2"},
    {q:"كم عدد أفلام هاري بوتر؟",a:"ثمانية",qE:"How many Harry Potter films?",aE:"Eight"},
    {q:"ما اسم سمكة فيلم البحث عن نيمو؟",a:"نيمو",qE:"Fish in Finding Nemo?",aE:"Nemo"},
    {q:"من بطل المهمة المستحيلة؟",a:"توم كروز",qE:"Star of Mission Impossible?",aE:"Tom Cruise"},
    {q:"ما الاسم الحقيقي لسبايدرمان؟",a:"بيتر باركر",qE:"Spider-Man's real name?",aE:"Peter Parker"},
    {q:"كم عدد أحجار الإنفينيتي؟",a:"ستة",qE:"How many Infinity Stones?",aE:"Six"},
    {q:"من مخرج فيلم تايتانيك؟",a:"جيمس كاميرون",qE:"Director of Titanic?",aE:"James Cameron"},
    {q:"ما اسم أميرة فيلم علاء الدين؟",a:"ياسمين",qE:"Princess in Aladdin?",aE:"Jasmine"},
    {q:"ما أكثر لعبة فيديو مبيعاً في التاريخ؟",a:"ماينكرافت",qE:"Best-selling video game ever?",aE:"Minecraft"},
    {q:"ما اسم مملكة إلسا في فروزن؟",a:"أرنديل",qE:"Elsa's kingdom in Frozen?",aE:"Arendelle"},
    {q:"من يرتدي القناع الأسود والعباءة؟",a:"باتمان",qE:"Hero with black mask and cape?",aE:"Batman"},
    {q:"ما الشخصية الرئيسية في لعبة ماريو؟",a:"ماريو",qE:"Main character in Mario?",aE:"Mario"},
    {q:"ما اسم والد سيمبا في الأسد الملك؟",a:"موفاسا",qE:"Simba's father in Lion King?",aE:"Mufasa"},
    {q:"من يلعب دور آيرون مان؟",a:"روبرت داوني جونيور",qE:"Who plays Iron Man?",aE:"Robert Downey Jr."},
    {q:"ما اسم سلحفاة كونغ فو باندا؟",a:"أوغواي",qE:"Turtle master in Kung Fu Panda?",aE:"Oogway"},
    {q:"ما لعبة البناء والبقاء الشهيرة؟",a:"ماينكرافت",qE:"Famous block building game?",aE:"Minecraft"},
    {q:"من صوّت ميكي ماوس في الأصل؟",a:"والت ديزني",qE:"Who originally voiced Mickey Mouse?",aE:"Walt Disney"},
    {q:"ما اسم ساحر هاري بوتر الشرير؟",a:"فولدمورت",qE:"Villain in Harry Potter?",aE:"Voldemort"},
    {q:"في أي عام صدر أول فيلم أفنجرز؟",a:"2012",qE:"First Avengers movie year?",aE:"2012"},
    {q:"ما اللعبة الشهيرة بمعركة 100 لاعب؟",a:"فورتنايت",qE:"Famous 100-player battle royale?",aE:"Fortnite"},
    {q:"ما اسم الأخطبوط في سبونج بوب؟",a:"شفيق",qE:"Octopus in SpongeBob?",aE:"Squidward"},
    {q:"من يلعب دور جاك في تايتانيك؟",a:"ليوناردو دي كابريو",qE:"Who plays Jack in Titanic?",aE:"Leonardo DiCaprio"},
    {q:"ما اسم الأسد في نارنيا؟",a:"أصلان",qE:"Lion in Narnia?",aE:"Aslan"},
    {q:"ما اسم الساحرة في فيلم حورية البحر الصغيرة؟",a:"أورسولا",qE:"Witch in The Little Mermaid?",aE:"Ursula"},
  ],
  technology: [
    {q:"من أسس شركة أبل؟",a:"ستيف جوبز",qE:"Who founded Apple?",aE:"Steve Jobs"},
    {q:"ما أشهر محرك بحث؟",a:"غوغل",qE:"Most famous search engine?",aE:"Google"},
    {q:"من أسس فيسبوك؟",a:"مارك زوكربيرغ",qE:"Who founded Facebook?",aE:"Mark Zuckerberg"},
    {q:"ما نظام الهواتف الأشهر؟",a:"أندرويد",qE:"Most popular mobile OS?",aE:"Android"},
    {q:"من اخترع الويب؟",a:"تيم بيرنرز لي",qE:"Who invented the Web?",aE:"Tim Berners-Lee"},
    {q:"ما لغة البرمجة الأشهر للويب؟",a:"جافاسكريبت",qE:"Most used web language?",aE:"JavaScript"},
    {q:"ما أول هاتف ذكي من أبل؟",a:"آيفون",qE:"Apple's first smartphone?",aE:"iPhone"},
    {q:"ما اسم مساعد أبل الصوتي؟",a:"سيري",qE:"Apple's voice assistant?",aE:"Siri"},
    {q:"من أسس أمازون؟",a:"جيف بيزوس",qE:"Who founded Amazon?",aE:"Jeff Bezos"},
    {q:"ما أشهر عملة رقمية؟",a:"بيتكوين",qE:"Most famous cryptocurrency?",aE:"Bitcoin"},
    {q:"ما نظام تشغيل مايكروسوفت؟",a:"ويندوز",qE:"Microsoft's OS?",aE:"Windows"},
    {q:"من أسس مايكروسوفت؟",a:"بيل غيتس",qE:"Who founded Microsoft?",aE:"Bill Gates"},
    {q:"ما تيسلا مشهورة بتصنيعه؟",a:"سيارات كهربائية",qE:"What does Tesla make?",aE:"Electric cars"},
    {q:"ما هو يوتيوب؟",a:"منصة فيديو",qE:"What is YouTube?",aE:"Video platform"},
    {q:"ما اسم مساعد غوغل؟",a:"غوغل أسيستانت",qE:"Google's voice assistant?",aE:"Google Assistant"},
    {q:"ما أشهر تطبيق تواصل في العالم العربي؟",a:"واتساب",qE:"Most popular messaging app in Arab world?",aE:"WhatsApp"},
    {q:"من أسس تويتر؟",a:"جاك دورسي",qE:"Who founded Twitter?",aE:"Jack Dorsey"},
    {q:"ما أشهر منصة ألعاب من سوني؟",a:"بلايستيشن",qE:"Sony's gaming platform?",aE:"PlayStation"},
    {q:"ما هو ChatGPT؟",a:"ذكاء اصطناعي",qE:"What is ChatGPT?",aE:"AI chatbot"},
    {q:"ما أول لغة برمجة عالية المستوى؟",a:"فورتران",qE:"First high-level programming language?",aE:"Fortran"},
    {q:"ما المصطلح التقني لربط الأجهزة لاسلكياً قريبة؟",a:"بلوتوث",qE:"Short-range wireless tech?",aE:"Bluetooth"},
    {q:"ما أشهر موقع تواصل مهني؟",a:"لينكد إن",qE:"Most famous professional social network?",aE:"LinkedIn"},
    {q:"من أسس شركة تيسلا؟",a:"إيلون ماسك",qE:"Who founded Tesla?",aE:"Elon Musk"},
    {q:"ما اسم منصة مايكروسوفت للألعاب؟",a:"إكسبوكس",qE:"Microsoft's gaming console?",aE:"Xbox"},
    {q:"ما أشهر نظام للذكاء الاصطناعي التوليدي؟",a:"ChatGPT",qE:"Most famous generative AI?",aE:"ChatGPT"},
  ],
  food: [
    {q:"ما الفاكهة الأكثر استهلاكاً؟",a:"الموز",qE:"Most consumed fruit?",aE:"Banana"},
    {q:"من أين نشأت البيتزا؟",a:"إيطاليا",qE:"Where did pizza originate?",aE:"Italy"},
    {q:"ما المكون الرئيسي للشوكولاتة؟",a:"الكاكاو",qE:"Main ingredient in chocolate?",aE:"Cocoa"},
    {q:"ما الأكلة الشهيرة في اليابان؟",a:"السوشي",qE:"Famous Japanese dish?",aE:"Sushi"},
    {q:"ما أغلى توابل في العالم؟",a:"الزعفران",qE:"Most expensive spice?",aE:"Saffron"},
    {q:"ما يجعل الخبز ينتفخ؟",a:"الخميرة",qE:"What makes bread rise?",aE:"Yeast"},
    {q:"ما طعام الباندا المفضل؟",a:"الخيزران",qE:"What do pandas eat?",aE:"Bamboo"},
    {q:"ما مشروب حبوب البن؟",a:"القهوة",qE:"Drink from coffee beans?",aE:"Coffee"},
    {q:"ما الخضرة التي تبكيك؟",a:"البصل",qE:"Vegetable that makes you cry?",aE:"Onion"},
    {q:"من أين يُصنع السكر؟",a:"قصب السكر",qE:"Where is sugar made from?",aE:"Sugarcane"},
    {q:"ما الجبن المستخدم في البيتزا؟",a:"موتزاريلا",qE:"Cheese on pizza?",aE:"Mozzarella"},
    {q:"ما المادة الحلوة من النحل؟",a:"العسل",qE:"Sweet substance from bees?",aE:"Honey"},
    {q:"من أين نشأ الهمبرغر؟",a:"ألمانيا",qE:"Where did hamburger originate?",aE:"Germany"},
    {q:"ما الطبق الوطني للمكسيك؟",a:"التاكو",qE:"National dish of Mexico?",aE:"Taco"},
    {q:"ما الأكلة السعودية الشهيرة؟",a:"الكبسة",qE:"Famous Saudi dish?",aE:"Kabsa"},
    {q:"ما الفاكهة المشهورة بملكة الفواكه؟",a:"المنغوستين",qE:"Queen of fruits?",aE:"Mangosteen"},
    {q:"ما أشهر مشروب عربي تقليدي؟",a:"القهوة العربية",qE:"Famous traditional Arab drink?",aE:"Arabic coffee"},
    {q:"ما الطعام الإيطالي من عجين طويل؟",a:"الباستا",qE:"Italian long dough food?",aE:"Pasta"},
    {q:"ما الفاكهة الاستوائية بقشرة شوكية؟",a:"الأناناس",qE:"Tropical fruit with spiky skin?",aE:"Pineapple"},
    {q:"ما الطبق اللبناني المشهور من الحمص؟",a:"الحمص",qE:"Famous Lebanese chickpea dish?",aE:"Hummus"},
    {q:"ما الفاكهة ذات القشرة الصفراء المنحنية؟",a:"الموز",qE:"Yellow curved fruit?",aE:"Banana"},
    {q:"ما أشهر أكلة مصرية شعبية؟",a:"الكشري",qE:"Famous Egyptian street food?",aE:"Koshari"},
    {q:"ما المشروب الغازي الأشهر عالمياً؟",a:"كوكاكولا",qE:"Most famous soda?",aE:"Coca-Cola"},
    {q:"ما الطبق الهندي الشهير بالتوابل الحارة؟",a:"الكاري",qE:"Famous spicy Indian dish?",aE:"Curry"},
    {q:"ما الثمرة التي تصنع منها الجواكامولي؟",a:"الأفوكادو",qE:"Fruit used to make guacamole?",aE:"Avocado"},
  ],
  islam: [
    {q:"كم عدد أركان الإسلام؟",a:"خمسة",qE:"How many pillars of Islam?",aE:"Five"},
    {q:"كم سورة في القرآن؟",a:"114",qE:"Surahs in the Quran?",aE:"114"},
    {q:"ما أطول سورة في القرآن؟",a:"البقرة",qE:"Longest surah?",aE:"Al-Baqarah"},
    {q:"كم صلاة مفروضة في اليوم؟",a:"خمس",qE:"Daily obligatory prayers?",aE:"Five"},
    {q:"ما شهر الصيام؟",a:"رمضان",qE:"Month of fasting?",aE:"Ramadan"},
    {q:"أين تقع الكعبة؟",a:"مكة",qE:"Where is the Kaaba?",aE:"Mecca",altE:["Makkah"]},
    {q:"كم نبياً ذُكر في القرآن؟",a:"25",qE:"Prophets mentioned in Quran?",aE:"25"},
    {q:"ما أول مسجد في الإسلام؟",a:"مسجد قباء",qE:"First mosque in Islam?",aE:"Quba Mosque"},
    {q:"ما أقصر سورة في القرآن؟",a:"الكوثر",qE:"Shortest surah?",aE:"Al-Kawthar"},
    {q:"متى كانت الهجرة النبوية؟",a:"622 ميلادي",qE:"When was the Hijra?",aE:"622 CE"},
    {q:"ما السورة المسماة قلب القرآن؟",a:"يس",qE:"Surah called heart of Quran?",aE:"Ya-Sin"},
    {q:"ما اسم زوجة النبي الأولى؟",a:"خديجة",qE:"Prophet's first wife?",aE:"Khadijah"},
    {q:"ما الركن الخامس في الإسلام؟",a:"الحج",qE:"Fifth pillar of Islam?",aE:"Hajj"},
    {q:"ما اسم أول غزوة؟",a:"بدر",qE:"First major battle in Islam?",aE:"Badr"},
    {q:"ما الركن الثالث في الإسلام؟",a:"الزكاة",qE:"Third pillar of Islam?",aE:"Zakat"},
    {q:"كم جزءاً في القرآن؟",a:"ثلاثون",qE:"Parts (juz) in Quran?",aE:"Thirty"},
    {q:"ما الركن الأول في الإسلام؟",a:"الشهادتان",qE:"First pillar of Islam?",aE:"Shahada"},
    {q:"ما اسم صلاة قبل الفجر؟",a:"قيام الليل",qE:"Prayer before Fajr?",aE:"Qiyam al-Layl",altE:["Night prayer","Tahajjud"],alt:["التهجد"]},
    {q:"ما اسم الملك المسؤول عن الوحي؟",a:"جبريل",qE:"Angel of revelation?",aE:"Jibreel",altE:["Gabriel","Jibril"],alt:["جبرائيل"]},
    {q:"ما الليلة المباركة في رمضان؟",a:"ليلة القدر",qE:"Blessed night in Ramadan?",aE:"Laylat al-Qadr"},
    {q:"كم ركعة في صلاة الظهر؟",a:"أربع",qE:"Rakahs in Dhuhr prayer?",aE:"Four"},
    {q:"ما اسم عم النبي الذي نصره؟",a:"حمزة",qE:"Prophet's uncle who supported him?",aE:"Hamza"},
    {q:"في أي شهر هجري يكون الحج؟",a:"ذو الحجة",qE:"Hajj month?",aE:"Dhul Hijjah"},
    {q:"ما أول ما نزل من القرآن؟",a:"اقرأ",qE:"First word revealed in Quran?",aE:"Iqra",altE:["Read"]},
    {q:"كم عدد الخلفاء الراشدين؟",a:"أربعة",qE:"How many Rashidun caliphs?",aE:"Four"},
  ],
  arabic: [
    {q:"ما عاصمة الإمارات؟",a:"أبو ظبي",qE:"Capital of UAE?",aE:"Abu Dhabi"},
    {q:"ما أكبر دولة عربية مساحة؟",a:"الجزائر",qE:"Largest Arab country by area?",aE:"Algeria"},
    {q:"كم عدد الدول العربية؟",a:"22",qE:"How many Arab countries?",aE:"22"},
    {q:"ما البحر بين مصر والسعودية؟",a:"الأحمر",qE:"Sea between Egypt and Saudi?",aE:"Red Sea"},
    {q:"ما أصغر دولة عربية مساحة؟",a:"البحرين",qE:"Smallest Arab country?",aE:"Bahrain"},
    {q:"ما أشهر معلم في دبي؟",a:"برج خليفة",qE:"Famous landmark in Dubai?",aE:"Burj Khalifa"},
    {q:"ما عاصمة المغرب؟",a:"الرباط",qE:"Capital of Morocco?",aE:"Rabat"},
    {q:"ما عملة السعودية؟",a:"الريال",qE:"Currency of Saudi Arabia?",aE:"Riyal"},
    {q:"ما عاصمة العراق؟",a:"بغداد",qE:"Capital of Iraq?",aE:"Baghdad"},
    {q:"ما عاصمة لبنان؟",a:"بيروت",qE:"Capital of Lebanon?",aE:"Beirut"},
    {q:"ما عاصمة الأردن؟",a:"عمّان",qE:"Capital of Jordan?",aE:"Amman"},
    {q:"ما عاصمة الكويت؟",a:"الكويت",qE:"Capital of Kuwait?",aE:"Kuwait City"},
    {q:"ما عاصمة قطر؟",a:"الدوحة",qE:"Capital of Qatar?",aE:"Doha"},
    {q:"ما عاصمة عُمان؟",a:"مسقط",qE:"Capital of Oman?",aE:"Muscat"},
    {q:"ما أشهر أكلة عربية مشتركة؟",a:"الحمص",qE:"Shared Arab dish?",aE:"Hummus"},
    {q:"ما عاصمة تونس؟",a:"تونس",qE:"Capital of Tunisia?",aE:"Tunis"},
    {q:"ما عاصمة ليبيا؟",a:"طرابلس",qE:"Capital of Libya?",aE:"Tripoli"},
    {q:"ما عاصمة السودان؟",a:"الخرطوم",qE:"Capital of Sudan?",aE:"Khartoum"},
    {q:"ما عاصمة اليمن؟",a:"صنعاء",qE:"Capital of Yemen?",aE:"Sanaa"},
    {q:"ما عاصمة سوريا؟",a:"دمشق",qE:"Capital of Syria?",aE:"Damascus"},
    {q:"ما أطول برج في العالم العربي؟",a:"برج خليفة",qE:"Tallest tower in Arab world?",aE:"Burj Khalifa"},
    {q:"ما عاصمة البحرين؟",a:"المنامة",qE:"Capital of Bahrain?",aE:"Manama"},
    {q:"ما عاصمة الجزائر؟",a:"الجزائر",qE:"Capital of Algeria?",aE:"Algiers"},
    {q:"ما المضيق الذي يربط الخليج العربي بخليج عمان؟",a:"هرمز",qE:"Strait connecting Persian Gulf to Gulf of Oman?",aE:"Hormuz"},
    {q:"ما العملة الرسمية لمصر؟",a:"الجنيه المصري",qE:"Currency of Egypt?",aE:"Egyptian Pound"},
  ],
  literature: [
    {q:"من كتب البؤساء؟",a:"فيكتور هوغو",qE:"Who wrote Les Misérables?",aE:"Victor Hugo"},
    {q:"من مؤلف هاملت؟",a:"شكسبير",qE:"Who wrote Hamlet?",aE:"Shakespeare"},
    {q:"من كتب الأمير الصغير؟",a:"سانت إكزوبيري",qE:"Who wrote The Little Prince?",aE:"Saint-Exupéry"},
    {q:"من كتب 1984؟",a:"جورج أورويل",qE:"Who wrote 1984?",aE:"George Orwell"},
    {q:"من مؤلف هاري بوتر؟",a:"رولينغ",qE:"Who wrote Harry Potter?",aE:"J.K. Rowling"},
    {q:"من كتب الحرب والسلام؟",a:"تولستوي",qE:"Who wrote War and Peace?",aE:"Tolstoy"},
    {q:"من مؤلف دون كيشوت؟",a:"سرفانتس",qE:"Who wrote Don Quixote?",aE:"Cervantes"},
    {q:"من كتب الجريمة والعقاب؟",a:"دوستويفسكي",qE:"Who wrote Crime and Punishment?",aE:"Dostoevsky"},
    {q:"من كتب مزرعة الحيوان؟",a:"أورويل",qE:"Who wrote Animal Farm?",aE:"Orwell"},
    {q:"من مؤلف ألف ليلة وليلة؟",a:"مجهول",qE:"Who wrote 1001 Nights?",aE:"Unknown"},
    {q:"من هو الشاعر أمير الشعراء؟",a:"أحمد شوقي",qE:"Prince of Poets in Arabic?",aE:"Ahmad Shawqi"},
    {q:"من كتب المقدمة؟",a:"ابن خلدون",qE:"Who wrote The Muqaddimah?",aE:"Ibn Khaldun"},
    {q:"من كتب مئة عام من العزلة؟",a:"ماركيز",qE:"Who wrote 100 Years of Solitude?",aE:"García Márquez"},
    {q:"من كتب الشيخ والبحر؟",a:"همنغواي",qE:"Who wrote The Old Man and the Sea?",aE:"Hemingway"},
    {q:"بأي لغة كُتبت الإلياذة؟",a:"اليونانية",qE:"Language of the Iliad?",aE:"Greek"},
    {q:"من كتب كليلة ودمنة بالعربية؟",a:"ابن المقفع",qE:"Arabic translator of Kalila and Dimna?",aE:"Ibn al-Muqaffa"},
    {q:"من مؤلف البخلاء؟",a:"الجاحظ",qE:"Who wrote Al-Bukhala (The Misers)?",aE:"Al-Jahiz"},
    {q:"من كتب لا تحزن؟",a:"عائض القرني",qE:"Who wrote Don't Be Sad?",aE:"Aaidh al-Qarni"},
    {q:"من كتب رواية العجوز والبحر؟",a:"همنغواي",qE:"Who wrote The Old Man and the Sea?",aE:"Hemingway"},
    {q:"ما أشهر مسرحيات شكسبير التراجيدية؟",a:"هاملت",qE:"Shakespeare's most famous tragedy?",aE:"Hamlet"},
    {q:"من كتب رواية الخيميائي؟",a:"باولو كويلو",qE:"Who wrote The Alchemist?",aE:"Paulo Coelho"},
    {q:"من كتب رحلة ابن بطوطة؟",a:"ابن بطوطة",qE:"Who wrote the Rihla?",aE:"Ibn Battuta"},
    {q:"من مؤلف روميو وجولييت؟",a:"شكسبير",qE:"Who wrote Romeo and Juliet?",aE:"Shakespeare"},
    {q:"من كتب البؤساء بالفرنسية؟",a:"فيكتور هوغو",qE:"Who wrote Les Misérables in French?",aE:"Victor Hugo"},
    {q:"من كتب رواية أنا كارنينا؟",a:"تولستوي",qE:"Who wrote Anna Karenina?",aE:"Tolstoy"},
  ],
  animals: [
    {q:"ما أكبر حيوان بري؟",a:"الفيل الأفريقي",qE:"Largest land animal?",aE:"African elephant"},
    {q:"ما الحيوان الذي ينام واقفاً؟",a:"الحصان",qE:"Animal that sleeps standing?",aE:"Horse"},
    {q:"كم رجل للعنكبوت؟",a:"ثمانية",qE:"How many legs does a spider have?",aE:"Eight"},
    {q:"ما الطائر الوحيد الذي يطير للخلف؟",a:"الطنان",qE:"Only bird that flies backwards?",aE:"Hummingbird"},
    {q:"ما الحيوان الذي لا يشرب الماء أبداً؟",a:"الكوالا",qE:"Animal that rarely drinks water?",aE:"Koala"},
    {q:"كم قلب للأخطبوط؟",a:"ثلاثة",qE:"How many hearts does an octopus have?",aE:"Three"},
    {q:"ما أسرع طائر في العالم؟",a:"الشاهين",qE:"Fastest bird?",aE:"Peregrine falcon"},
    {q:"ما الحيوان الذي يغير لونه؟",a:"الحرباء",qE:"Animal that changes color?",aE:"Chameleon"},
    {q:"كم سنة يعيش السلحفاة تقريباً؟",a:"أكثر من 100",qE:"How long can a tortoise live?",aE:"Over 100 years"},
    {q:"ما أذكى حيوان بعد الإنسان؟",a:"الدلفين",qE:"Smartest animal after humans?",aE:"Dolphin"},
    {q:"ما الحيوان المعروف بملك الغابة؟",a:"الأسد",qE:"King of the jungle?",aE:"Lion"},
    {q:"كم عدد أرجل النملة؟",a:"ستة",qE:"How many legs does an ant have?",aE:"Six"},
    {q:"ما أكبر طائر في العالم؟",a:"النعامة",qE:"Largest bird?",aE:"Ostrich"},
    {q:"ما الحيوان الذي يحمل بيته على ظهره؟",a:"السلحفاة",qE:"Animal that carries its home?",aE:"Turtle",altE:["Tortoise"]},
    {q:"ما أطول حيوان بحري؟",a:"الحوت الأزرق",qE:"Longest marine animal?",aE:"Blue whale"},
    {q:"ما الحيوان الذي يُنتج الحرير؟",a:"دودة القز",qE:"Animal that produces silk?",aE:"Silkworm"},
    {q:"ما الحيوان ذو الرقبة الأطول؟",a:"الزرافة",qE:"Animal with the longest neck?",aE:"Giraffe"},
    {q:"ما الحشرة التي تصنع العسل؟",a:"النحلة",qE:"Insect that makes honey?",aE:"Bee"},
    {q:"كم سن للقرش تقريباً؟",a:"3000",qE:"Approximate teeth of a shark?",aE:"Around 3000"},
    {q:"ما الحيوان الذي يعيش في القطب الجنوبي؟",a:"البطريق",qE:"Animal living in Antarctica?",aE:"Penguin"},
    {q:"ما الحيوان الأبطأ في العالم؟",a:"الكسلان",qE:"Slowest animal?",aE:"Sloth"},
    {q:"ما الحيوان الذي يستطيع الطيران والسباحة؟",a:"البط",qE:"Animal that can fly and swim?",aE:"Duck"},
    {q:"ما صوت الأسد؟",a:"زئير",qE:"Sound of a lion?",aE:"Roar"},
    {q:"ما الحيوان الذي يعيش في الماء ولا يتنفس تحته؟",a:"الحوت",qE:"Marine mammal that breathes air?",aE:"Whale"},
    {q:"ما الحيوان الذي يملك أكبر عيون؟",a:"الحبار العملاق",qE:"Animal with the largest eyes?",aE:"Giant squid"},
  ],
  flags: [
    {q:"أي دولة علمها أخضر فقط؟",a:"ليبيا",qE:"Country with an all-green flag (historical)?",aE:"Libya"},
    {q:"ما الدولة التي علمها يحمل نجمة داوود؟",a:"إسرائيل",qE:"Country with Star of David on flag?",aE:"Israel"},
    {q:"أي دولة علمها أحمر بدائرة بيضاء؟",a:"اليابان",qE:"Country with red circle on white?",aE:"Japan"},
    {q:"ما الدولة التي علمها ورقة شجرة القيقب؟",a:"كندا",qE:"Country with maple leaf flag?",aE:"Canada"},
    {q:"أي دولة علمها به نجمة وهلال؟",a:"تركيا",qE:"Country with star and crescent?",aE:"Turkey"},
    {q:"ما لون علم فرنسا؟",a:"أزرق أبيض أحمر",qE:"Colors of French flag?",aE:"Blue, white, red"},
    {q:"أي دولة علمها مثلث أزرق ونجوم؟",a:"الولايات المتحدة",qE:"Country with blue triangle and stars?",aE:"United States"},
    {q:"ما الدولة التي علمها يحمل تنيناً أحمر؟",a:"ويلز",qE:"Country with red dragon on flag?",aE:"Wales"},
    {q:"أي دولة علمها أخضر أبيض برتقالي؟",a:"إيرلندا",qE:"Country with green white orange flag?",aE:"Ireland"},
    {q:"ما الدولة التي علمها به صليب أبيض على أحمر؟",a:"سويسرا",qE:"Country with white cross on red?",aE:"Switzerland"},
    {q:"أي دولة عربية علمها أسود أبيض أخضر مع مثلث أحمر؟",a:"الأردن",qE:"Arab country with black, white, green and red triangle?",aE:"Jordan"},
    {q:"ما الدولة التي علمها يحمل نسراً؟",a:"مصر",qE:"Country with eagle on flag?",aE:"Egypt"},
    {q:"أي دولة علمها أصفر أزرق أحمر أفقي؟",a:"كولومبيا",qE:"Country with yellow blue red horizontal?",aE:"Colombia"},
    {q:"ما الدولة التي علمها دائرة خضراء على أصفر؟",a:"البرازيل",qE:"Country with green diamond on yellow?",aE:"Brazil"},
    {q:"أي دولة علمها نجمتان فقط؟",a:"سوريا",qE:"Country with exactly two stars on flag?",aE:"Syria"},
    {q:"ما اللون المشترك في معظم الأعلام العربية؟",a:"الأخضر",qE:"Common color in most Arab flags?",aE:"Green"},
    {q:"أي دولة علمها به شعار السيفين والنخلة؟",a:"السعودية",qE:"Flag with two swords and palm tree?",aE:"Saudi Arabia"},
    {q:"ما الدولة التي علمها أزرق ونجمة بيضاء؟",a:"الصومال",qE:"Blue flag with white star?",aE:"Somalia"},
    {q:"أي دولة علمها يحمل شمساً صفراء؟",a:"الأرجنتين",qE:"Country with yellow sun on flag?",aE:"Argentina"},
    {q:"ما الدولة ذات العلم الأحمر بنجمة خضراء؟",a:"المغرب",qE:"Red flag with green star?",aE:"Morocco"},
    {q:"أي دولة آسيوية علمها برتقالي أبيض أخضر؟",a:"الهند",qE:"Asian country with orange white green flag?",aE:"India"},
    {q:"ما الدولة التي علمها يحمل أسداً؟",a:"سريلانكا",qE:"Country with lion on flag?",aE:"Sri Lanka"},
    {q:"أي دولة أوروبية علمها أزرق بنجوم صفراء؟",a:"الاتحاد الأوروبي",qE:"Blue flag with yellow stars (not a country)?",aE:"European Union"},
    {q:"ما الدولة التي علمها مربعات حمراء وبيضاء؟",a:"كرواتيا",qE:"Country with red and white checkered flag?",aE:"Croatia"},
    {q:"أي دولة علمها يحتوي على خريطتها؟",a:"قبرص",qE:"Country with its map on the flag?",aE:"Cyprus"},
  ],
};

const CATEGORIES = Object.keys(QUESTIONS);

module.exports = { QUESTIONS, CATEGORIES };
